name: Egocentric Check
on: [push, pull_request]

jobs:
  check-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check if my name is in README
        run: |
          if grep -qi "Giulia" README.md; then
            echo "Hi Giulia!"
          else
            echo "ERROR: Name not found, try again."
            exit 1
          fi
